yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: node-modules

packageExtensions:
  "react-scripts@5.0.0":
    peerDependencies:
      autoprefixer: "^10.0.2"

  "react-dev-utils@12.0.0":
    peerDependencies:
      typescript: ">=2.7"
      webpack: ">= 4"

  "eslint-config-react-app@7.0.0":
    dependencies:
      "@babel/plugin-syntax-flow": ^7.14.5
      "@babel/plugin-transform-react-jsx": ^7.14.9

  #firebase
  "@firebase/analytics-compat@0.1.8":
    peerDependencies:
      "@firebase/app": "0.x"

  "@firebase/app-check-compat@0.2.5":
    peerDependencies:
      "@firebase/app": "0.x"

  "@firebase/auth-compat@0.2.11":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"

  "@firebase/database@0.12.7":
    peerDependencies:
      "@firebase/app-types": "0.x"

  "@firebase/firestore-compat@0.1.16":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"

  "@firebase/database-compat@0.1.7":
    peerDependencies:
      "@firebase/app-types": "0.x"

  "@firebase/functions-compat@0.1.11":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"

  "@firebase/functions@0.7.10":
    peerDependencies:
      "@firebase/app-types": "0.x"

  "@firebase/messaging-compat@0.1.11":
    peerDependencies:
      "@firebase/app": "0.x"
  "@firebase/performance-compat@0.1.7":
    peerDependencies:
      "@firebase/app": "0.x"
  "@firebase/remote-config-compat@0.1.7":
    peerDependencies:
      "@firebase/app": "0.x"
  "@firebase/storage-compat@0.1.12":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
